version: "3"
networks: 
  crowd-projects-app-network:
services:

  mysql-db:
    container_name: mysql-db
    image: mysql/mysql-server:latest
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sergey 
      MYSQL_DATABASE: projects_db_docker
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose:
      - 3307
    networks: 
      - crowd-projects-app-network

  cloud-config-server:
    container_name: cloud-config-server
    image: manju0707/crowd-projects-app-microservice-docker-cloud-config-server:0.0.1-SNAPSHOT
    build: ./cloud-config-server
    ports:
      - "8888:8888"
    # restart: always
    networks: 
      - crowd-projects-app-network

  eureka-naming-server:
    container_name: eureka-naming-server
    image: manju0707/crowd-projects-app-microservice-docker-eureka-naming-server:0.0.1-SNAPSHOT
    build: ./eureka-naming-server
    ports:
      - "8761:8761"
    # restart: always
    depends_on:
      - cloud-config-server
    networks: 
      - crowd-projects-app-network

  zuul-api-gateway-server:
    container_name: zuul-api-gateway-server
    image: manju0707/crowd-projects-app-microservice-docker-zuul-api-gateway-server:0.0.1-SNAPSHOT
    build: ./zuul-api-gateway-server
    ports:
      - "8765:8765"
    # restart: always
    depends_on:
      - cloud-config-server
      - eureka-naming-server
    networks:
      - crowd-projects-app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaServer:e12ur810Re2kA@eureka-naming-server:8761/eureka
      - CLOUD_CONFIG_SERVER_URL=http://cloud-config-server:8888
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z cloud-config-server 8888); do sleep 5; echo 'Waiting for cloud-config-server services to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
      "

  oauth2-authentication-server:
    container_name: oauth2-authentication-server
    image: manju0707/crowd-projects-app-microservice-docker-oauth2-authentication-server:0.0.1-SNAPSHOT
    build: ./oauth2-authentication-server
    ports:
      - "9898:9898"
    # restart: always
    depends_on:
      - mysql-db
      - cloud-config-server
      - eureka-naming-server
      - zuul-api-gateway-server
    networks:
      - crowd-projects-app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaServer:e12ur810Re2kA@eureka-naming-server:8761/eureka
      - CLOUD_CONFIG_SERVER_URL=http://cloud-config-server:8888
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z cloud-config-server 8888); do sleep 5; echo 'Waiting for cloud-config-server services to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
      "

  user-service:
    container_name: user-service
    image: manju0707/crowd-projects-app-microservice-docker-user-service:0.0.1-SNAPSHOT
    build: ./user-service
    ports:
      - "9000:9000"
    # restart: always
    depends_on:
      - mysql-db
      - cloud-config-server
      - eureka-naming-server
      - zuul-api-gateway-server
      - oauth2-authentication-server
    networks:
      - crowd-projects-app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaServer:e12ur810Re2kA@eureka-naming-server:8761/eureka
      - CLOUD_CONFIG_SERVER_URL=http://cloud-config-server:8888
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z cloud-config-server 8888); do sleep 5; echo 'Waiting for cloud-config-server services to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
      "

  project-service:
    container_name: project-service
    image: manju0707/crowd-projects-app-microservice-docker-project-service:0.0.1-SNAPSHOT
    build: ./project-service
    ports:
      - "9900:9900"
    # restart: always
    depends_on:
      - mysql-db
      - cloud-config-server
      - eureka-naming-server
      - zuul-api-gateway-server
      - oauth2-authentication-server
    networks:
      - crowd-projects-app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaServer:e12ur810Re2kA@eureka-naming-server:8761/eureka
      - CLOUD_CONFIG_SERVER_URL=http://cloud-config-server:8888
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z cloud-config-server 8888); do sleep 5; echo 'Waiting for cloud-config-server services to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
      "