version: "3"
networks: 
  sample-app-network:
services:
  cloud-config-server:
    container_name: cloud-config-server
    image: manju0707/sample-springboot-microservice-docker-cloud-config-server:0.0.1-SNAPSHOT
    # build: ./cloud-config-server
    ports:
      - "8888:8888"
    # restart: always
    networks: 
      - sample-app-network

  eureka-naming-server:
    container_name: eureka-naming-server
    image: manju0707/sample-springboot-microservice-docker-eureka-naming-server:0.0.1-SNAPSHOT
    # build: ./eureka-naming-server
    ports:
      - "8761:8761"
    # restart: always
    depends_on:
      - cloud-config-server
    networks: 
      - sample-app-network

  zuul-api-gateway-server:
    container_name: zuul-api-gateway-server
    image: manju0707/sample-springboot-microservice-docker-zuul-api-gateway-server:0.0.1-SNAPSHOT
    # build: ./zuul-api-gateway-server
    ports:
      - "8765:8765"
    # restart: always
    depends_on:
      - cloud-config-server
      - eureka-naming-server
    networks:
      - sample-app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaServer:e12ur810Re2kA@eureka-naming-server:8761/eureka
      - CLOUD_CONFIG_SERVER_URL=http://cloud-config-server:8888
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z cloud-config-server 8888); do sleep 5; echo 'Waiting for cloud-config-server services to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
      "

  oauth2-authentication-server:
    container_name: oauth2-authentication-server
    image: manju0707/sample-springboot-microservice-docker-oauth2-authentication-server:0.0.1-SNAPSHOT
    # build: ./oauth2-authentication-server
    ports:
      - "9898:9898"
    # restart: always
    depends_on:
      - cloud-config-server
      - eureka-naming-server
      - zuul-api-gateway-server
    networks:
      - sample-app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaServer:e12ur810Re2kA@eureka-naming-server:8761/eureka
      - CLOUD_CONFIG_SERVER_URL=http://cloud-config-server:8888
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z cloud-config-server 8888); do sleep 5; echo 'Waiting for cloud-config-server services to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
      "

  user-service:
    container_name: user-service
    image: manju0707/sample-springboot-microservice-docker-user-service:0.0.1-SNAPSHOT
    # build: ./user-service
    ports:
      - "9000:9000"
    # restart: always
    depends_on:
      - cloud-config-server
      - eureka-naming-server
      - zuul-api-gateway-server
    networks:
      - sample-app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaServer:e12ur810Re2kA@eureka-naming-server:8761/eureka
      - CLOUD_CONFIG_SERVER_URL=http://cloud-config-server:8888
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z cloud-config-server 8888); do sleep 5; echo 'Waiting for cloud-config-server services to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
      "

  group-service:
    container_name: group-service
    image: manju0707/sample-springboot-microservice-docker-group-service:0.0.1-SNAPSHOT
    # build: ./group-service
    ports:
      - "9900:9900"
    # restart: always
    depends_on:
      - cloud-config-server
      - eureka-naming-server
      - zuul-api-gateway-server
    networks:
      - sample-app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaServer:e12ur810Re2kA@eureka-naming-server:8761/eureka
      - CLOUD_CONFIG_SERVER_URL=http://cloud-config-server:8888
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z cloud-config-server 8888); do sleep 5; echo 'Waiting for cloud-config-server services to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
      "